apps/models.go
Match
https://github.com/ketch-com/ketch-cli/blob/main/assets/schemas/manifest.json#L33-L40
https://github.com/ketch-com/ketch-cli/blob/main/assets/schemas/manifest.json#L66-L79
=> fix(app): capability + category mapping

apps/publish.go, cmd/ketch/commands/publish.go, flags/flags.go
Per discusssion with @smalexan, removing --create flag that allows create + publish until such time we implement separate create only functionality
=> fix(create): remove create flag

action.yml
=> fix(action): remove --create from github action

apps/models.go, assets/schemas/manifest.json
https://switchbit.atlassian.net/browse/KD-1045
Depends on https://github.com/ketch-com/commissary/pull/116
=> feat(KD-1045): Vendor updates and auto install. Part 1

apps/models.go
> Add tag orchestration to enum
=> chore(enum): add tag orchestration to enum

apps/publish.go
> Added verbose logging to App creation
> After creating app should be a detailed log entry in the console
=> fix(logs_verbose): add verbose logging to app creation

apps/publish.go
> Look for the correct prefix for template code validation
=> fix(validate): correct prefix for code validation

README.md, apps/models.go, apps/publish.go
> Read all manifest files in a directory
> Add purposeTemplateCollections
> Validate cookie codes
=> fix(publish): directory + purposeTemplateCollections

apps/publish.go, apps/validate.go
> Validate all files in a directory
=> feat(validate): validate dir

apps/models.go
> Add missing purpose template fields
=> fix(purpose-template): add missing fields

apps/publish.go
> log response on error in unmarshal
=> fix(resp): log on error

apps/models.go
=> fix(purposeTemplate): convert data type

apps/publish.go
=> fix: nil pointer dereference if manifest has no logo

.github/workflows/ci.yml
This PR adds `SNYK_AUTH_TOKEN` env var to GitHub Actions CI. We need this to get `docker scan` working.
No testing required.
=> chore: add SNYK_AUTH_TOKEN env var to CI

assets/schemas/manifest.json
> Added "datasales_ccpa" purpose
"datasales_ccpa" should be supported in the manifest
=> fix(datasales_ccpa): add datasales_ccpa purpose

assets/schemas/manifest.json, go.sum
Add new tag event `tag.batchUpdate` to validate
=> chore(tag): add tag event to validation

assets/schemas/manifest.json
> Added `tag.migration` event to manifest validation schema
=> chore: googletag tag.migrate event

pkg/transponder/configure.go
Update ketch cli configure message
Tested local
=> chore(transponder-configure-msg): update transponder configure message

winch.yml
Use .EXE extension for Windows build
Local build
N/A
=> fix: use .exe extension for windows build

assets/schemas/manifest.json
> updated schema to support get canonical right
> Description here
> Fix [KD-3042](https://ketch-com.atlassian.net/browse/KD-3042)
=> chore: updated schema to support get canonical right

winch.yml
=> fix: release artifacts

pkg/transponder/configure.go, pkg/transponder/ls.go
Better error reporting
Ran locally, manually
=> fix: better error reporting
